spring.application.name=EduForge

# DB Config (use valid existing username)
spring.datasource.url=jdbc:postgresql://localhost:5432/eduforge
spring.datasource.username=harshgohil
spring.datasource.password=idkman@123

# Hibernate
    spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Static files
spring.web.resources.static-locations=file:uploads/

logging.level.root=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=edu.forge001@gmail.com
spring.mail.password=vudzrbhccqsvnsya
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true